version: '3.9'

# External network
networks:
  caddyweb:
    external: true

volumes:
  mongodb-data:


services:

  # FastAPI backend
  toucan-api:
    container_name: toucan-api
    build:
      context: ./toucan-backend
    depends_on:
      - toucan-db
    ports:
      - "8001:8001"
    stop_signal: SIGINT
    command: uvicorn toucan-backend.cms.main:app --reload --host 0.0.0.0 --port 8001
    env_file:
      - .env
    volumes:
      - '.:/ubuntu:delegated'
    networks:
      - caddyweb


  # MongoDB database
  toucan-db:
    image: mongo:5.0
    container_name: toucan-db
    command: mongod --port 27017
    volumes:
      - mongodb-data:/data/toucan-db
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - caddyweb


  #  Frontend Next app
  toucan-next-frontend:
    build:
      context: ./toucan-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: yarn start
    networks:
      - caddyweb
